'use strict';
// Generated by build-bootstrap.py; sealed native admission is required.
const bindings = (() => {
const module = { exports: {} };
'use strict';

// Native code creates and seals this record after task/policy/input admission.
// Parsing this record alone never grants execution or containment authority.
const { createHash } = require('node:crypto');
const FD_MAX = 255;
const BINDING_MAX = 16 * 1024;
const sha256 = bytes => createHash('sha256').update(bytes).digest('hex');
const refuse = () => { throw Object.assign(new Error('invalid sealed npm binding'), { code: 'EBOUNDINPUT' }); };
const objectKeys = (value, keys) => value !== null && typeof value === 'object' &&
  !Array.isArray(value) && Object.keys(value).join(',') === keys;
const uint = (n, max) => Number.isSafeInteger(n) && n >= 0 && n <= max;
const digest = value => typeof value === 'string' && /^[0-9a-f]{64}$/.test(value);
const decimal64 = value => typeof value === 'string' && /^(?:0|[1-9][0-9]{0,19})$/.test(value) &&
  BigInt(value) <= 18446744073709551615n;
const operand = fd => `/proc/self/fd/${fd}`;

function decodeBinding (text, bindingFd) {
  if (typeof text !== 'string' || Buffer.byteLength(text) > BINDING_MAX ||
      !uint(bindingFd, FD_MAX) || bindingFd < 3) refuse();
  const value = JSON.parse(text);
  if (JSON.stringify(value) !== text ||
      !objectKeys(value, 'schema_version,contract,runtime,artifacts,target,cache,user_config,global_config') ||
      value.schema_version !== 1 || value.contract !== 'LocalLeafNoScriptsV1') refuse();
  const used = new Set([bindingFd]);
  const admitFd = fd => {
    if (!uint(fd, FD_MAX) || fd < 3 || used.has(fd)) refuse();
    used.add(fd);
  };
  if (!objectKeys(value.runtime, 'fd,sha256,size') || !digest(value.runtime.sha256) ||
      !uint(value.runtime.size, 64 * 1024 * 1024) || value.runtime.size < 12) refuse();
  admitFd(value.runtime.fd);
  if (!Array.isArray(value.artifacts) || value.artifacts.length < 1 || value.artifacts.length > 8) refuse();
  let total = 0;
  const names = new Set();
  for (const row of value.artifacts) {
    if (!objectKeys(row, 'fd,package_name,sha256,size') || typeof row.package_name !== 'string' ||
        !/^(?:@[a-z0-9][a-z0-9._-]*\/)?[a-z0-9][a-z0-9._-]*$/.test(row.package_name) ||
        row.package_name.length > 214 || names.has(row.package_name) || !digest(row.sha256) ||
        !uint(row.size, 32 * 1024 * 1024) || row.size === 0) refuse();
    total += row.size;
    if (total > 64 * 1024 * 1024) refuse();
    names.add(row.package_name);
    admitFd(row.fd);
  }
  for (const row of [value.target, value.cache]) {
    if (!objectKeys(row, 'fd,device,inode') || !decimal64(row.device) ||
        !decimal64(row.inode) || row.inode === '0') refuse();
    admitFd(row.fd);
  }
  if (value.target.device === value.cache.device && value.target.inode === value.cache.inode) refuse();
  for (const row of [value.user_config, value.global_config]) {
    if (!objectKeys(row, 'fd')) refuse();
    admitFd(row.fd);
  }
  for (const row of [value.runtime, ...value.artifacts, value.target, value.cache,
    value.user_config, value.global_config]) Object.freeze(row);
  Object.freeze(value.artifacts);
  return Object.freeze(value);
}

function readExact (fs, fd, size, limit) {
  if (!uint(size, limit)) refuse();
  const before = fs.fstatSync(fd, { bigint: true });
  if (!before.isFile() || before.size !== BigInt(size)) refuse();
  const bytes = Buffer.alloc(size);
  let offset = 0;
  while (offset < size) {
    const got = fs.readSync(fd, bytes, offset, size - offset, offset);
    if (!Number.isSafeInteger(got) || got <= 0 || got > size - offset) refuse();
    offset += got;
  }
  const after = fs.fstatSync(fd, { bigint: true });
  if (!after.isFile() || after.dev !== before.dev || after.ino !== before.ino || after.size !== before.size) refuse();
  return bytes;
}

function readBinding (fs, argv) {
  if (!Array.isArray(argv) || argv.length !== 2 || !/^(?:[3-9]|[1-9][0-9]{1,2})$/.test(argv[1])) refuse();
  const fd = Number(argv[1]);
  if (fd > FD_MAX) refuse();
  const stat = fs.fstatSync(fd, { bigint: true });
  if (!stat.isFile() || stat.size < 1n || stat.size > BigInt(BINDING_MAX)) refuse();
  const bytes = readExact(fs, fd, Number(stat.size), BINDING_MAX);
  // Round-trip UTF-8 rejects replacement decoding before canonical JSON checks.
  const text = bytes.toString('utf8');
  if (!Buffer.from(text).equals(bytes)) refuse();
  return decodeBinding(text, fd);
}

function verifyInputs (fs, binding) {
  for (const row of [binding.target, binding.cache]) {
    const stat = fs.fstatSync(row.fd, { bigint: true });
    if (!stat.isDirectory() || stat.dev.toString() !== row.device || stat.ino.toString() !== row.inode) refuse();
  }
  readExact(fs, binding.user_config.fd, 0, 0);
  readExact(fs, binding.global_config.fd, 0, 0);
  const pack = readExact(fs, binding.runtime.fd, binding.runtime.size, 64 * 1024 * 1024);
  if (sha256(pack) !== binding.runtime.sha256) refuse();
  const artifacts = binding.artifacts.map(row => {
    const bytes = readExact(fs, row.fd, row.size, 32 * 1024 * 1024);
    if (sha256(bytes) !== row.sha256) refuse();
    return Object.freeze({ fd: row.fd, name: row.package_name, sha256: row.sha256,
      sha512: createHash('sha512').update(bytes).digest('hex') });
  });
  return Object.freeze({ pack, artifacts: Object.freeze(artifacts) });
}

module.exports = { BINDING_MAX, decodeBinding, readBinding, readExact, verifyInputs, operand };

return module.exports;
})();
const runtimePack = (() => {
const module = { exports: {} };
'use strict';

const path = require('node:path').posix;
const { createHash } = require('node:crypto');
const NODE_SHA256 = '9507fea66ea788dfb2bbef1380ef6ef8940697ef1de15bee62b279e6cfef035c';
const NPM_TREE_SHA256 = '3a34157a11136a4e01f691b297bed524edee9b8cc3bc30e34ad195b17dd8c60e';
const PREFIX = 'usr/local/lib/node_modules/npm/';
const EXTRA_PATHS = new Set([
  'usr/lib/aarch64-linux-gnu/libatomic.so.1', 'usr/lib/aarch64-linux-gnu/libatomic.so.1.2.0',
  'usr/lib/aarch64-linux-gnu/libdl.so.2', 'usr/lib/aarch64-linux-gnu/libm.so.6',
  'usr/lib/aarch64-linux-gnu/libstdc++.so.6', 'usr/lib/aarch64-linux-gnu/libstdc++.so.6.0.30',
  'usr/lib/aarch64-linux-gnu/libgcc_s.so.1', 'usr/lib/aarch64-linux-gnu/libpthread.so.0',
  'usr/lib/aarch64-linux-gnu/libc.so.6', 'usr/lib/aarch64-linux-gnu/ld-linux-aarch64.so.1',
  'usr/lib/ld-linux-aarch64.so.1', 'etc/ld.so.cache', 'etc/passwd', 'etc/group',
  'etc/nsswitch.conf', 'etc/hosts', 'etc/resolv.conf', 'etc/tirith-empty-openssl.cnf',
]);
const sha256 = bytes => createHash('sha256').update(bytes).digest('hex');
const refuse = () => { throw Object.assign(new Error('invalid sealed npm runtime pack'), { code: 'EBOUNDRUNTIME' }); };
const keys = (value, expected) => value !== null && typeof value === 'object' &&
  !Array.isArray(value) && Object.keys(value).join(',') === expected;
const uint = n => Number.isSafeInteger(n) && n >= 0;

function decodeRuntimePack (bytes) {
  if (!Buffer.isBuffer(bytes) || bytes.length < 12 || bytes.length > 64 * 1024 * 1024 ||
      !bytes.subarray(0, 8).equals(Buffer.from('TIRNPM01'))) refuse();
  const length = bytes.readUInt32BE(8);
  if (length > 1024 * 1024 || length > bytes.length - 12) refuse();
  const raw = bytes.subarray(12, 12 + length);
  const text = raw.toString('utf8');
  if (!Buffer.from(text).equals(raw)) refuse();
  const manifest = JSON.parse(text);
  if (JSON.stringify(manifest) !== text ||
      !keys(manifest, 'schema_version,node_sha256,npm_tree_sha256,entries') ||
      manifest.schema_version !== 1 || manifest.node_sha256 !== NODE_SHA256 ||
      manifest.npm_tree_sha256 !== NPM_TREE_SHA256 || !Array.isArray(manifest.entries) ||
      manifest.entries.length < 1 || manifest.entries.length > 4096) refuse();
  const names = new Set();
  const directories = new Map();
  const npm = [];
  let previous = '';
  let offset = 0;
  for (const entry of manifest.entries) {
    if (!keys(entry, 'path,executable,size,sha256,offset') || typeof entry.path !== 'string' ||
        entry.path.length > 4096 || /[^\x20-\x7e]|[\\:]/.test(entry.path) ||
        entry.path.split('/').some(part => !part || part === '.' || part === '..') ||
        entry.path.split('/').length > 72 ||
        !(entry.path.startsWith(PREFIX) && entry.path.length > PREFIX.length || EXTRA_PATHS.has(entry.path)) ||
        typeof entry.executable !== 'boolean' || !uint(entry.size) || entry.size > 8 * 1024 * 1024 ||
        !uint(entry.offset) || entry.offset !== offset || typeof entry.sha256 !== 'string' ||
        !/^[0-9a-f]{64}$/.test(entry.sha256) || entry.path <= previous ||
        entry.size > bytes.length - 12 - length - offset) refuse();
    const name = entry.path.toLowerCase();
    if (names.has(name) || directories.has(name)) refuse();
    for (let parent = path.dirname(entry.path); parent !== '.'; parent = path.dirname(parent)) {
      const folded = parent.toLowerCase();
      if (names.has(folded) || directories.has(folded) && directories.get(folded) !== parent) refuse();
      directories.set(folded, parent);
      if (directories.size > 16384) refuse();
    }
    const content = bytes.subarray(12 + length + offset, 12 + length + offset + entry.size);
    if (sha256(content) !== entry.sha256) refuse();
    if (entry.path.startsWith(PREFIX)) {
      npm.push(Object.freeze({ path: entry.path.slice(PREFIX.length), bytes: content, sha256: entry.sha256 }));
    }
    names.add(name);
    previous = entry.path;
    offset += entry.size;
  }
  if (12 + length + offset !== bytes.length || npm.length === 0) refuse();
  // Non-npm entries were validated but are never mounted or made JS modules.
  // Native code admits exact retained host libraries for this separate mode.
  return Object.freeze(npm);
}

module.exports = { decodeRuntimePack, NODE_SHA256, NPM_TREE_SHA256 };

return module.exports;
})();
const resolver = (() => {
const module = { exports: {} };
'use strict';
// Resolves only the byte inventory admitted by the sealed runtime decoder.
// This module does not grant native execution or filesystem authority.
const path = require('node:path').posix;
const { createHash } = require('node:crypto');
const { isBuiltin } = require('node:module');
const { pathToFileURL, fileURLToPath } = require('node:url');

function closedResolver(entries, root = '/tirith-runtime/npm') {
  if (!Array.isArray(entries) || entries.length < 1 || entries.length > 4096 ||
      !/^\/[A-Za-z0-9_/-]+$/.test(root) || path.normalize(root) !== root || root === '/') {
    throw new Error('invalid bounded closure');
  }
  const files = new Map();
  const directories = new Set([root]);
  const packages = new Map();
  let total = 0;
  const fail = (message, code = 'MODULE_NOT_FOUND') => {
    throw Object.assign(new Error(message), { code });
  };
  const inside = p => p === root || p.startsWith(root + '/');
  for (const row of entries) {
    if (!row || typeof row.path !== 'string' ||
        !/^[A-Za-z0-9._@+/-]+$/.test(row.path) || row.path.startsWith('/') ||
        row.path.split('/').some(x => !x || x === '.' || x === '..') ||
        !Buffer.isBuffer(row.bytes) || row.bytes.length > 8 * 1024 * 1024 ||
        !/^[a-f0-9]{64}$/.test(row.sha256)) fail('invalid closure entry');
    const p = root + '/' + row.path;
    if (files.has(p) || directories.has(p)) fail('duplicate or colliding closure entry');
    const bytes = Buffer.from(row.bytes);
    if (createHash('sha256').update(bytes).digest('hex') !== row.sha256) fail('closure hash mismatch');
    total += bytes.length;
    if (total > 64 * 1024 * 1024) fail('closure byte limit');
    files.set(p, bytes);
    for (let d = path.dirname(p); inside(d); d = path.dirname(d)) {
      if (files.has(d)) fail('file/directory collision');
      directories.add(d);
      if (directories.size > 16384) fail('closure directory limit');
      if (d === root) break;
    }
  }
  const json = dir => {
    if (packages.has(dir)) return packages.get(dir);
    const b = files.get(dir + '/package.json');
    let value = null;
    if (b) {
      value = JSON.parse(b.toString('utf8'));
      if (!value || typeof value !== 'object' || Array.isArray(value)) fail('invalid package metadata');
    }
    packages.set(dir, value);
    return value;
  };
  const scope = p => {
    for (let d = path.dirname(p); inside(d); d = path.dirname(d)) {
      const pkg = json(d);
      if (pkg) return { dir: d, pkg };
      if (d === root || path.basename(d) === 'node_modules') break;
    }
    return null;
  };
  const requireFile = p => {
    if (!inside(p)) fail('module outside captured closure');
    for (const candidate of [p, p + '.js', p + '.json']) {
      if (files.has(candidate)) return candidate;
    }
    return null;
  };
  const requirePath = p => {
    const direct = requireFile(p);
    if (direct) return direct;
    if (!directories.has(p)) return null;
    const pkg = json(p);
    if (typeof pkg?.main === 'string' && pkg.main) {
      const target = path.resolve(p, pkg.main);
      if (!inside(target)) fail('package main escapes captured closure');
      const main = requireFile(target) || requireFile(path.join(target, 'index'));
      if (main) return main;
    }
    return requireFile(path.join(p, 'index'));
  };
  const exact = p => {
    if (!inside(p) || !files.has(p)) fail('module not in captured closure: ' + p);
    return p;
  };
  const target = (value, dir, conditions, star, depth = 0) => {
    if (depth > 16) fail('conditional export depth');
    if (value === null) return null;
    if (typeof value === 'string') {
      if (!value.startsWith('./') || /[\\%?#\0]/.test(value)) fail('unsupported package target');
      const text = star === undefined ? value : value.replaceAll('*', star);
      if (text.includes('*') || text.split('/').slice(1).some(x => x === '..' || x === 'node_modules')) {
        fail('unsupported package target traversal');
      }
      const p = path.resolve(dir, text);
      if (!p.startsWith(dir + '/')) fail('package target escapes its package');
      return exact(p);
    }
    if (Array.isArray(value)) {
      // Pinned closure arrays use a valid first arm. Do not emulate permissive
      // invalid-target fallback: unsupported arms deliberately refuse.
      for (const v of value) {
        const result = target(v, dir, conditions, star, depth + 1);
        if (result !== undefined) return result;
      }
      return undefined;
    }
    if (value && typeof value === 'object') {
      for (const [condition, v] of Object.entries(value)) {
        if (condition.startsWith('.') || /^\d+$/.test(condition)) fail('unsupported conditional export');
        if (condition === 'default' || conditions.has(condition)) {
          const result = target(v, dir, conditions, star, depth + 1);
          if (result !== undefined) return result;
        }
      }
      return undefined;
    }
    fail('unsupported package target shape');
  };
  const mapped = (map, key, dir, conditions, kind) => {
    if (kind === 'exports' && (typeof map === 'string' || Array.isArray(map) ||
        map === null || Object.keys(map).every(x => !x.startsWith('.')))) {
      if (key !== '.') fail('package subpath is not exported', 'ERR_PACKAGE_PATH_NOT_EXPORTED');
      return target(map, dir, conditions);
    }
    if (!map || typeof map !== 'object' || Array.isArray(map)) fail('unsupported package map');
    if (Object.hasOwn(map, key)) return target(map[key], dir, conditions);
    const patterns = Object.keys(map).filter(x => x.split('*').length === 2)
      .sort((a, b) => b.indexOf('*') - a.indexOf('*') || b.length - a.length);
    for (const pattern of patterns) {
      const [prefix, suffix] = pattern.split('*');
      if (key.startsWith(prefix) && key.endsWith(suffix) && key.length >= prefix.length + suffix.length) {
        return target(map[pattern], dir, conditions, key.slice(prefix.length, key.length - suffix.length));
      }
    }
    fail('package map has no captured target', kind === 'imports' ? 'ERR_PACKAGE_IMPORT_NOT_DEFINED' : 'ERR_PACKAGE_PATH_NOT_EXPORTED');
  };
  const parseURL = value => {
    const u = new URL(value);
    if (u.protocol !== 'file:' || u.host || u.search || u.hash) fail('unsupported module URL');
    const p = fileURLToPath(u);
    if (!inside(p)) fail('module URL outside captured closure');
    return p;
  };
  const resolvePath = (specifier, parent, conditionNames) => {
    if (typeof specifier !== 'string' || specifier.length > 4096 || /[\\\0]/.test(specifier)) fail('invalid module specifier');
    if (isBuiltin(specifier)) return specifier.startsWith('node:') ? specifier : 'node:' + specifier;
    const conditions = new Set(conditionNames);
    const isRequire = conditions.has('require');
    const p = parseURL(parent);
    if (!files.has(p)) fail('module parent is outside captured inventory');
    if (specifier.startsWith('file:')) {
      const requested = parseURL(specifier);
      return isRequire ? requirePath(requested) || fail('missing captured file') : exact(requested);
    }
    if (specifier.startsWith('/') || specifier === '.' || specifier === '..' ||
        specifier.startsWith('./') || specifier.startsWith('../')) {
      const requested = path.resolve(path.dirname(p), specifier);
      return isRequire ? requirePath(requested) || fail('missing captured relative module') : exact(requested);
    }
    if (specifier.startsWith('#')) {
      const s = scope(p);
      if (!s?.pkg.imports) fail('unbound internal import', 'ERR_PACKAGE_IMPORT_NOT_DEFINED');
      return mapped(s.pkg.imports, specifier, s.dir, conditions, 'imports') || fail('disabled internal import');
    }
    if (specifier.includes(':') || specifier.includes('%') || specifier.includes('?')) fail('unsupported bare specifier');
    const parts = specifier.split('/');
    const count = specifier.startsWith('@') ? 2 : 1;
    if (parts.length < count || parts.some(x => !x || x === '.' || x === '..')) fail('invalid package name');
    const name = parts.slice(0, count).join('/');
    const sub = parts.length === count ? '.' : './' + parts.slice(count).join('/');
    const self = scope(p);
    const candidates = [];
    if (self?.pkg.name === name && self.pkg.exports !== undefined) candidates.push(self.dir);
    for (let d = path.dirname(p); inside(d); d = path.dirname(d)) {
      if (path.basename(d) !== 'node_modules') candidates.push(path.join(d, 'node_modules', name));
      if (d === root) break;
    }
    for (const dir of candidates) {
      if (!directories.has(dir)) continue;
      const pkg = json(dir);
      if (pkg?.exports !== undefined) {
        return mapped(pkg.exports, sub, dir, conditions, 'exports') || fail('disabled package export');
      }
      const requested = sub === '.' ? dir : path.join(dir, sub);
      const result = isRequire || sub === '.' ? requirePath(requested) : files.has(requested) ? requested : null;
      if (result) return result;
    }
    fail('package is outside captured closure: ' + name);
  };
  const format = p => {
    if (p.endsWith('.json')) return 'json';
    if (p.endsWith('.cjs')) return 'commonjs';
    if (p.endsWith('.mjs')) return 'module';
    if (p.endsWith('.js')) return scope(p)?.pkg.type === 'module' ? 'module' : 'commonjs';
    fail('unsupported captured module format');
  };
  return Object.freeze({
    resolve(specifier, parentURL, conditions = ['node', 'require']) {
      const p = resolvePath(specifier, parentURL, conditions);
      if (p.startsWith('node:')) return Object.freeze({ url: p, format: 'builtin', shortCircuit: true });
      return Object.freeze({ url: pathToFileURL(p).href, format: format(p), shortCircuit: true });
    },
    load(url) {
      const p = parseURL(url);
      return { format: format(p), source: Buffer.from(files.get(exact(p))), shortCircuit: true };
    },
    root,
  });
}
module.exports = { closedResolver };

return module.exports;
})();
const descriptorBridge = (() => {
const module = { exports: {} };
'use strict'

// Rows are derived from bytes read from retained native-admitted sealed inputs.
// Native descriptor admission, containment and output verification are separate.
const { Buffer } = require('node:buffer')

const refusal = reason => Object.assign(new Error(reason), { code: 'EBOUNDINPUT' })

function descriptorBridge (stockNpa, rows) {
  if (typeof stockNpa !== 'function' || typeof stockNpa.resolve !== 'function' ||
      typeof stockNpa.Result !== 'function' || !Array.isArray(rows) ||
      rows.length < 1 || rows.length > 8) {
    throw refusal('invalid closed descriptor model')
  }
  const bindings = new Map()
  const names = new Set()
  for (const row of rows) {
    if (!row || Object.keys(row).sort().join(',') !== 'fd,name,sha256,sha512' ||
        !Number.isInteger(row.fd) || row.fd < 3 || row.fd > 255 ||
        bindings.has(`/proc/self/fd/${row.fd}`) || typeof row.name !== 'string' ||
        !/^(?:@[a-z0-9][a-z0-9._-]*\/)?[a-z0-9][a-z0-9._-]*$/.test(row.name) ||
        row.name.length > 214 || names.has(row.name) ||
        typeof row.sha256 !== 'string' || !/^[0-9a-f]{64}$/.test(row.sha256) ||
        typeof row.sha512 !== 'string' || !/^[0-9a-f]{128}$/.test(row.sha512)) {
      throw refusal('invalid bound descriptor row')
    }
    names.add(row.name)
    const path = `/proc/self/fd/${row.fd}`
    bindings.set(path, Object.freeze({
      path,
      name: row.name,
      sha256Integrity: `sha256-${Buffer.from(row.sha256, 'hex').toString('base64')}`,
      integrity: `sha512-${Buffer.from(row.sha512, 'hex').toString('base64')}`,
    }))
  }

  function adapt (result) {
    // Stock parsing remains authoritative for canonical path and raw spelling.
    // This is the only parser behavior changed by the model.
    if (result instanceof stockNpa.Result && result.type === 'directory' &&
        bindings.has(result.fetchSpec)) {
      result.type = 'file'
    }
    return result
  }
  const npa = (arg, where) => adapt(stockNpa(arg, where))
  npa.resolve = (name, spec, where, arg) => adapt(stockNpa.resolve(name, spec, where, arg))
  npa.Result = stockNpa.Result
  npa.toPurl = stockNpa.toPurl

  function expectedIntegrity (value, bound) {
    const parts = String(value).split(' ')
    return parts.length >= 1 && parts.length <= 2 && new Set(parts).size === parts.length &&
      parts.every(part => part === bound.integrity || part === bound.sha256Integrity)
  }

  function guardFetcher (stockGet) {
    if (typeof stockGet !== 'function') {
      throw refusal('missing stock fetcher')
    }
    return (rawSpec, opts = {}) => {
      const spec = npa(rawSpec, opts.where)
      const bound = bindings.get(spec.fetchSpec)
      if (!(spec instanceof stockNpa.Result) || spec.type !== 'file' || !bound ||
          spec.registry || (spec.name !== undefined && spec.name !== bound.name) ||
          (opts.resolved !== undefined && opts.resolved !== null && opts.resolved !== bound.path && opts.resolved !== `file:${bound.path}`) ||
          (opts.integrity !== undefined && opts.integrity !== null &&
            !expectedIntegrity(opts.integrity, bound))) {
        throw refusal('fetch is outside the exact approved descriptor binding')
      }
      // Native seal/FD identity checks precede the bootstrap.
      return stockGet(spec, {
        ...opts,
        resolved: bound.path,
        integrity: bound.integrity,
        allowRegistry: 'none',
        allowRemote: 'none',
        allowGit: 'none',
        allowDirectory: 'none',
        allowFile: 'all',
      })
    }
  }
  return Object.freeze({ npa, guardFetcher })
}

module.exports = { descriptorBridge }

return module.exports;
})();
const projectConfig = (() => {
const module = { exports: {} };
'use strict';

const path = require('node:path').posix;
const { fileURLToPath } = require('node:url');

// npm 11.19.0 Config.loadProjectConfig resolves exactly prefix/.npmrc, then
// #loadFile calls the destructured fs/promises.readFile(file, 'utf8'). Install
// this routing before any npm module is loaded. Keep stock parsing/source flow.
function bindEmptyProjectConfig (fsPromises, targetOperand) {
  if (!/^\/proc\/self\/fd\/(?:[3-9]|[1-9][0-9]{1,2})$/.test(targetOperand) ||
      Number(targetOperand.slice(targetOperand.lastIndexOf('/') + 1)) > 255 ||
      typeof fsPromises.readFile !== 'function') throw new Error('invalid project config binding');
  const expected = path.resolve(targetOperand, '.npmrc');
  const original = fsPromises.readFile;
  fsPromises.readFile = async function (file, options) {
    let candidate = file;
    if (Buffer.isBuffer(file)) candidate = file.toString('utf8');
    else if (file instanceof URL && file.protocol === 'file:') candidate = fileURLToPath(file);
    if (typeof candidate === 'string' && path.isAbsolute(candidate) && path.resolve(candidate) === expected) {
      if (file !== expected || options !== 'utf8') throw new Error('unsupported project config read shape');
      return '';
    }
    return original.call(this, file, options);
  };
}

module.exports = { bindEmptyProjectConfig };

return module.exports;
})();
const entry = (() => {
const module = { exports: {} };
'use strict';

// The bundler supplies these private modules as lexical values. No external
// path, caller-supplied source, npm configuration or module fallback is loaded.
function runSealedNpm (bindings, runtimePack, resolver, descriptorBridge, projectConfig) {
  const fs = require('node:fs');
  const fsPromises = require('node:fs/promises');
  const moduleApi = require('node:module');
  const path = require('node:path').posix;
  const vfs = require('node:vfs');
  if (process.version !== 'v26.7.0' || process.platform !== 'linux' || process.arch !== 'arm64') {
    throw new Error('unsupported sealed npm runtime');
  }
  const binding = bindings.readBinding(fs, process.argv);
  const verified = bindings.verifyInputs(fs, binding);
  const entries = runtimePack.decodeRuntimePack(verified.pack);
  const root = '/tirith-runtime/npm';
  const adapter = resolver.closedResolver(entries, root);
  const memory = vfs.create({ emitExperimentalWarning: false });
  for (const row of entries) {
    const file = '/' + row.path;
    memory.mkdirSync(path.dirname(file), { recursive: true });
    memory.writeFileSync(file, row.bytes);
  }
  memory.provider.setReadOnly();
  memory.mount(root);
  if (memory.readonly !== true) throw new Error('runtime is not read-only');
  moduleApi.registerHooks({
    resolve (specifier, context, nextResolve) {
      if (moduleApi.isBuiltin(specifier)) return nextResolve(specifier, context);
      return adapter.resolve(specifier, context.parentURL, context.conditions);
    },
    load (url, context, nextLoad) {
      if (url.startsWith('node:')) return nextLoad(url, context);
      return adapter.load(url);
    },
  });

  const target = bindings.operand(binding.target.fd);
  const cache = bindings.operand(binding.cache.fd);
  // Native code already verified both config descriptors are sealed empty
  // bytes. Distinct operands preserve npm's per-source uniqueness invariant.
  projectConfig.bindEmptyProjectConfig(fsPromises, target);
  const entry = root + '/bin/npm-cli.js';
  const req = moduleApi.createRequire(entry);
  const npaPath = req.resolve('npm-package-arg');
  const stockNpa = req('npm-package-arg');
  const bridge = descriptorBridge.descriptorBridge(stockNpa, verified.artifacts);
  if (req.cache[npaPath]?.exports !== stockNpa) throw new Error('npm argument module changed');
  req.cache[npaPath].exports = bridge.npa;
  const fetcher = req('pacote/lib/fetcher.js');
  if (req.cache[req.resolve('pacote')] !== undefined) throw new Error('npm fetcher loaded before binding');
  fetcher.get = bridge.guardFetcher(fetcher.get);
  process.argv = [process.execPath, entry, 'install',
    '--offline', '--ignore-scripts', '--no-audit', '--no-fund', '--no-update-notifier',
    '--bin-links=false', '--package-lock=false', '--no-save', '--omit=dev', '--workspaces=false',
    '--allow-directory=none', '--allow-git=none', '--allow-remote=none', '--allow-file=all',
    `--prefix=${target}`, `--userconfig=${bindings.operand(binding.user_config.fd)}`,
    `--globalconfig=${bindings.operand(binding.global_config.fd)}`, `--cache=${cache}`,
    '--logs-max=0', '--loglevel=error', ...verified.artifacts.map(row => bindings.operand(row.fd))];
  // Stock npm owns normal config loading, command dispatch and exit behavior.
  // Native code independently verifies bytes, metadata and effect boundaries.
  req(entry);
}

module.exports = { runSealedNpm };

return module.exports;
})();
try {
  entry.runSealedNpm(bindings, runtimePack, resolver, descriptorBridge, projectConfig);
} catch {
  console.error('tirith: sealed npm bootstrap refused its bound inputs');
  process.exitCode = 78;
}
