# Generated by `tirith setup cline` on Windows. Do not edit; re-run setup to
# refresh it.
#
# Cline's Windows hook runtime runs this file with
#   pwsh -NoProfile -NonInteractive -ExecutionPolicy Bypass -File PreToolUse.ps1
# passing the PreToolUse event as JSON on stdin and reading the decision JSON
# from stdout. This script is the Windows counterpart of the POSIX `#!/bin/sh`
# wrapper: Cline injects no environment, so the Tirith path, the wire protocol,
# and the adapter location are baked in here, and it forwards stdin and stdout
# through the shared Python adapter unchanged.
$ErrorActionPreference = 'Stop'

$env:TIRITH_BIN = '__TIRITH_BIN__'
$env:TIRITH_HOOK_PROTOCOL = 'cline'

# Read the whole event before spawning, so a closed stdin cannot deadlock.
$raw = [Console]::In.ReadToEnd()

$python = Get-Command python3 -ErrorAction SilentlyContinue
if (-not $python) { $python = Get-Command python -ErrorAction SilentlyContinue }
if (-not $python) {
    # No interpreter to run the adapter. Cline runs the tool when a hook fails,
    # so a fail-open opt-out is honoured; otherwise cancel, matching the adapter.
    if ($env:TIRITH_FAIL_OPEN -eq '1') { Write-Output '{"cancel":false}'; exit 0 }
    Write-Output '{"cancel":true,"errorMessage":"tirith: python3 not found on PATH; install Python or set TIRITH_FAIL_OPEN=1"}'
    exit 0
}

$decision = $raw | & $python.Source '__ADAPTER_PATH__'
$code = $LASTEXITCODE

if (($code -ne 0) -and (-not $decision)) {
    if ($env:TIRITH_FAIL_OPEN -eq '1') { Write-Output '{"cancel":false}'; exit 0 }
    Write-Output '{"cancel":true,"errorMessage":"tirith: hook adapter exited without a decision"}'
    exit 0
}

Write-Output $decision
exit 0
