#!/usr/bin/env python3
"""Build/check the closed npm bootstrap from its six reviewed source modules."""
import argparse
import hashlib
import json
from pathlib import Path

PARTS = (
    ('bindings', 'bindings.cjs'),
    ('runtimePack', 'runtime-pack.cjs'),
    ('resolver', 'closed-resolver.cjs'),
    ('descriptorBridge', 'descriptor-bridge.cjs'),
    ('projectConfig', 'project-config.cjs'),
    ('entry', 'entry.cjs'),
)
GENERATED = Path('crates/tirith/src/cli/npm_sealed_bootstrap.cjs')
SOURCES = Path('tools/npm-bootstrap')
MAX_SOURCE_BYTES = 128 * 1024


def build_bundle(source_root):
    chunks = ["'use strict';\n// Generated by build-bootstrap.py; sealed native admission is required.\n"]
    hashes = {}
    for name, filename in PARTS:
        path = source_root / filename
        if path.is_symlink() or not path.is_file() or path.stat().st_size > MAX_SOURCE_BYTES:
            raise ValueError(f'invalid bounded bootstrap source: {filename}')
        source = path.read_bytes()
        if len(source) > MAX_SOURCE_BYTES:
            raise ValueError(f'bootstrap source exceeds bound: {filename}')
        hashes[filename] = hashlib.sha256(source).hexdigest()
        chunks.append(f'const {name} = (() => {{\nconst module = {{ exports: {{}} }};\n')
        chunks.append(source.decode('utf-8'))
        chunks.append('\nreturn module.exports;\n})();\n')
    chunks.append("try {\n  entry.runSealedNpm(bindings, runtimePack, resolver, descriptorBridge, projectConfig);\n")
    chunks.append("} catch {\n  console.error('tirith: sealed npm bootstrap refused its bound inputs');\n  process.exitCode = 78;\n}\n")
    bundle = ''.join(chunks).encode('utf-8')
    if len(bundle) > MAX_SOURCE_BYTES:
        raise ValueError('bootstrap exceeds native source bound')
    hashes[GENERATED.as_posix()] = hashlib.sha256(bundle).hexdigest()
    return bundle, (json.dumps(hashes, indent=2) + '\n').encode('utf-8')


def outputs(repo_root):
    bundle, manifest = build_bundle(repo_root / SOURCES)
    return ((repo_root / GENERATED, bundle),
            (repo_root / SOURCES / 'source-hashes.json', manifest))


def check(repo_root):
    for path, expected in outputs(repo_root):
        if path.is_symlink() or not path.is_file() or path.read_bytes() != expected:
            raise ValueError(f'generated bootstrap drift: {path.relative_to(repo_root)}')


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    action = parser.add_mutually_exclusive_group(required=True)
    action.add_argument('--check', action='store_true', help='verify without writing files')
    action.add_argument('--write', action='store_true', help='regenerate the fixed bundle and digest manifest')
    args = parser.parse_args()
    repo_root = Path(__file__).resolve().parents[2]
    try:
        if args.check:
            check(repo_root)
        else:
            for path, expected in outputs(repo_root):
                if path.is_symlink():
                    raise ValueError(f'generated destination is a symlink: {path}')
                path.write_bytes(expected)
    except (OSError, UnicodeError, ValueError) as error:
        parser.exit(1, f'{error}\n')


if __name__ == '__main__':
    main()
