#!/usr/bin/env python3
"""Build/check the closed npm bootstrap from its six reviewed source modules."""
import argparse
import hashlib
import json
from pathlib import Path

PARTS = (
    ('bindings', 'bindings.cjs'),
    ('runtimePack', 'runtime-pack.cjs'),
    ('resolver', 'closed-resolver.cjs'),
    ('descriptorBridge', 'descriptor-bridge.cjs'),
    ('projectConfig', 'project-config.cjs'),
    ('entry', 'entry.cjs'),
)
GENERATED = Path('crates/tirith/src/cli/npm_sealed_bootstrap.cjs')
SOURCES = Path('tools/npm-bootstrap')
MAX_SOURCE_BYTES = 128 * 1024

# This tail is exercised from the generated bytes by bootstrap-controls.cjs.
# Labels are closed literals; no caught message, stack, path or input is printed.
REFUSAL_TAIL = """let bootstrapStage = 'entry';
let diagnosticWrite;
try { diagnosticWrite = require('node:fs').writeSync; } catch { /* Refusal still runs. */ }
const diagnosticDescriptor = Object.getOwnPropertyDescriptor;
const diagnosticPrototype = Object.getPrototypeOf;
const setBootstrapStage = stage => {
  switch (stage) {
    case 'runtime': case 'binding': case 'inputs': case 'pack': case 'resolver':
    case 'vfs-create': case 'vfs-populate': case 'vfs-readonly': case 'vfs-mount':
    case 'module-hooks': case 'project-config': case 'npm-argument':
    case 'descriptor-bridge': case 'npm-fetcher': case 'npm-entry':
      bootstrapStage = stage; break;
    default: bootstrapStage = 'unknown';
  }
};
try {
  entry.runSealedNpm(bindings, runtimePack, resolver, descriptorBridge, projectConfig, setBootstrapStage);
} catch (error) {
  // Set refusal first: a closed/broken/nonblocking stderr must not replace it.
  process.exitCode = 78;
  let code = 'UNKNOWN';
  let name = 'Error';
  let reason = 'unclassified';
  try {
    const ownCode = diagnosticDescriptor(error, 'code')?.value;
    switch (ownCode) {
      case 'EBOUNDINPUT': case 'EBOUNDRUNTIME': case 'EPERM': case 'EACCES': case 'EBADF': case 'ENOENT':
      case 'EINVAL': case 'ENOSYS': case 'ENOMEM': case 'EIO': case 'ENOTDIR':
      case 'EROFS': case 'EEXIST': case 'MODULE_NOT_FOUND':
      case 'ERR_MODULE_NOT_FOUND': case 'ERR_INVALID_ARG_TYPE':
      case 'ERR_INVALID_ARG_VALUE': case 'ERR_INVALID_URL':
      case 'ERR_UNKNOWN_BUILTIN_MODULE': case 'ERR_ACCESS_DENIED':
      case 'ERR_PACKAGE_IMPORT_NOT_DEFINED': case 'ERR_PACKAGE_PATH_NOT_EXPORTED':
        code = ownCode;
    }
    const ownName = diagnosticDescriptor(error, 'name')?.value;
    const errorName = ownName === undefined
      ? diagnosticDescriptor(diagnosticPrototype(error), 'name')?.value : ownName;
    switch (errorName) {
      case 'Error': case 'TypeError': case 'RangeError': case 'SyntaxError':
      case 'ReferenceError': case 'URIError': case 'EvalError': name = errorName;
    }
    const message = diagnosticDescriptor(error, 'message')?.value;
    // Compare known source literals only; never copy a caught message or its
    // path-bearing suffix into output, and never invoke an exception getter.
    switch (message) {
      case 'unsupported sealed npm runtime': reason = 'unsupported-runtime'; break;
      case 'invalid sealed npm binding': reason = 'invalid-binding'; break;
      case 'invalid sealed npm runtime pack': reason = 'invalid-runtime-pack'; break;
      case 'runtime is not read-only': reason = 'readonly-check'; break;
      case 'npm argument module changed': reason = 'argument-module-changed'; break;
      case 'npm fetcher loaded before binding': reason = 'fetcher-loaded-early'; break;
      case 'invalid bounded closure': reason = 'invalid-closure'; break;
      case 'invalid closure entry': reason = 'invalid-closure-entry'; break;
      case 'duplicate or colliding closure entry': case 'file/directory collision': reason = 'closure-collision'; break;
      case 'closure hash mismatch': reason = 'closure-hash'; break;
      case 'closure byte limit': case 'closure directory limit': reason = 'closure-limit'; break;
      case 'invalid package metadata': reason = 'invalid-package-metadata'; break;
      case 'module outside captured closure': case 'module URL outside captured closure': reason = 'module-outside-closure'; break;
      case 'module parent is outside captured inventory': reason = 'module-parent-outside-inventory'; break;
      case 'package main escapes captured closure': case 'package target escapes its package': reason = 'package-target-escape'; break;
      case 'conditional export depth': reason = 'export-depth'; break;
      case 'unsupported package target': case 'unsupported package target traversal':
      case 'unsupported conditional export': case 'unsupported package target shape':
      case 'unsupported package map': reason = 'unsupported-package-target'; break;
      case 'package subpath is not exported': case 'package map has no captured target':
      case 'unbound internal import': case 'disabled internal import': case 'disabled package export': reason = 'package-target-unavailable'; break;
      case 'unsupported module URL': reason = 'unsupported-module-url'; break;
      case 'invalid module specifier': case 'unsupported bare specifier': case 'invalid package name': reason = 'invalid-module-specifier'; break;
      case 'missing captured file': case 'missing captured relative module': reason = 'missing-module'; break;
      case 'unsupported captured module format': reason = 'unsupported-module-format'; break;
      case 'invalid closed descriptor model': case 'invalid bound descriptor row': reason = 'invalid-descriptor-binding'; break;
      case 'missing stock fetcher': reason = 'missing-fetcher'; break;
      case 'fetch is outside the exact approved descriptor binding': reason = 'fetch-outside-binding'; break;
      case 'invalid project config binding': case 'unsupported project config read shape': reason = 'project-config-binding'; break;
      default:
        if (typeof message === 'string') {
          if (message.startsWith('module not in captured closure: ')) reason = 'module-not-in-inventory';
          else if (message.startsWith('package is outside captured closure: ')) reason = 'package-outside-closure';
        }
    }
  } catch { /* Proxy traps and invalid thrown values keep fixed fallback labels. */ }
  const text = `tirith: sealed npm bootstrap refused its bound inputs (stage=${bootstrapStage}, code=${code}, name=${name}, reason=${reason})\\n`;
  try {
    // Raw fd writing avoids libuv's lazy console/stdio adoption. Bound both
    // partial writes and retries; the public message is always below 256 bytes.
    let offset = 0;
    for (let attempt = 0; attempt < 8 && offset < text.length; attempt++) {
      const written = diagnosticWrite(2, text.slice(offset));
      if (!Number.isInteger(written) || written <= 0 || written > text.length - offset) break;
      offset += written;
    }
  } catch { /* Reporting is best effort; refusal remains 78. */ }
}
"""


def build_bundle(source_root):
    chunks = ["'use strict';\n// Generated by build-bootstrap.py; sealed native admission is required.\n"]
    hashes = {}
    for name, filename in PARTS:
        path = source_root / filename
        if path.is_symlink() or not path.is_file() or path.stat().st_size > MAX_SOURCE_BYTES:
            raise ValueError(f'invalid bounded bootstrap source: {filename}')
        source = path.read_bytes()
        if len(source) > MAX_SOURCE_BYTES:
            raise ValueError(f'bootstrap source exceeds bound: {filename}')
        hashes[filename] = hashlib.sha256(source).hexdigest()
        chunks.append(f'const {name} = (() => {{\nconst module = {{ exports: {{}} }};\n')
        chunks.append(source.decode('utf-8'))
        chunks.append('\nreturn module.exports;\n})();\n')
    chunks.append(REFUSAL_TAIL)
    bundle = ''.join(chunks).encode('utf-8')
    if len(bundle) > MAX_SOURCE_BYTES:
        raise ValueError('bootstrap exceeds native source bound')
    hashes[GENERATED.as_posix()] = hashlib.sha256(bundle).hexdigest()
    return bundle, (json.dumps(hashes, indent=2) + '\n').encode('utf-8')


def outputs(repo_root):
    bundle, manifest = build_bundle(repo_root / SOURCES)
    return ((repo_root / GENERATED, bundle),
            (repo_root / SOURCES / 'source-hashes.json', manifest))


def check(repo_root):
    for path, expected in outputs(repo_root):
        if path.is_symlink() or not path.is_file() or path.read_bytes() != expected:
            raise ValueError(f'generated bootstrap drift: {path.relative_to(repo_root)}')


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    action = parser.add_mutually_exclusive_group(required=True)
    action.add_argument('--check', action='store_true', help='verify without writing files')
    action.add_argument('--write', action='store_true', help='regenerate the fixed bundle and digest manifest')
    args = parser.parse_args()
    repo_root = Path(__file__).resolve().parents[2]
    try:
        if args.check:
            check(repo_root)
        else:
            for path, expected in outputs(repo_root):
                if path.is_symlink():
                    raise ValueError(f'generated destination is a symlink: {path}')
                path.write_bytes(expected)
    except (OSError, UnicodeError, ValueError) as error:
        parser.exit(1, f'{error}\n')


if __name__ == '__main__':
    main()
