#!/usr/bin/env python3
"""Render the human remediation view from canonical JSON without importing the importer."""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from collections import Counter
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[3]
HERE = Path(__file__).resolve().parent
SOURCE_INDEX = HERE / "source-index.json"
FINDINGS = HERE / "findings.json"
OUTPUT = ROOT / "main.md"


def file_sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def load(path: Path) -> Any:
    return json.loads(path.read_text(encoding="utf-8"))


def cell(value: Any) -> str:
    return str(value).replace("|", "\\|").replace("\n", " ")


def active_blockers(finding: dict[str, Any]) -> list[dict[str, Any]]:
    return [blocker for blocker in finding["blockers"] if blocker["closed_date"] is None]


def display_status(finding: dict[str, Any]) -> str:
    verification = finding["verification"]
    fixed = (
        finding["lifecycle"] == "merged_verified"
        and not active_blockers(finding)
        and finding["resolution_route"] != "upstream_candidate"
        and verification["merge_commit"] is not None
        and any(
            attempt["kind"] == "release"
            and attempt["head_sha"] == verification["merge_commit"]
            and attempt["result"] == "passed"
            for attempt in verification["attempts"]
        )
    )
    return "FIXED" if fixed else "OPEN"


def render(source_index: dict[str, Any], ledger: dict[str, Any]) -> str:
    source_rows = {row["source_id"]: row for row in source_index["sources"]}
    lifecycle_counts = Counter(item["lifecycle"] for item in ledger["findings"])
    severity_counts = Counter(item["severity"] for item in ledger["findings"])
    route_counts = Counter(item["resolution_route"] for item in ledger["findings"])
    blocker_count = sum(bool(active_blockers(item)) for item in ledger["findings"])
    merged = lifecycle_counts["merged_verified"]
    lines = [
        "# Security remediation ledger",
        "",
        "> Generated by `docs/security/remediation/render_main.py`. Do not edit this file by hand.",
        "",
        "This view tracks 135 immutable source rows mapped to 131 canonical remediation roots.",
        "Exact duplicate source rows inherit the lifecycle of their canonical root; source rows are never closed independently.",
        "",
        "## Summary",
        "",
        "| Measure | Count |",
        "|---|---:|",
        f"| Immutable source rows | {len(source_index['sources'])} |",
        f"| Canonical findings | {len(ledger['findings'])} |",
        f"| Merged and verified | {merged} |",
        f"| Not merged and verified | {len(ledger['findings']) - merged} |",
        f"| Findings with active blockers | {blocker_count} |",
        "",
        "### Generation inputs",
        "",
        "| Input | SHA-256 |",
        "|---|---|",
        f"| `source-index.json` | `{file_sha256(SOURCE_INDEX)}` |",
        f"| `findings.json` | `{file_sha256(FINDINGS)}` |",
        f"| `source-index.schema.json` | `{file_sha256(HERE / 'source-index.schema.json')}` |",
        f"| `findings.schema.json` | `{file_sha256(HERE / 'findings.schema.json')}` |",
        f"| `evidence-bundle.schema.json` | `{file_sha256(HERE / 'evidence-bundle.schema.json')}` |",
        f"| `render_main.py` | `{file_sha256(Path(__file__))}` |",
        "",
        "### Source accounting",
        "",
        "| Report | Rows |",
        "|---|---:|",
    ]
    for report_id in source_index["report_order"]:
        lines.append(
            f"| {report_id} | {source_index['expected_counts']['by_report'][report_id]} |"
        )
    lines.extend(["", "### Lifecycle", "", "| Lifecycle | Count |", "|---|---:|"])
    for lifecycle in ledger["allowed_lifecycles"]:
        lines.append(f"| {lifecycle} | {lifecycle_counts[lifecycle]} |")
    lines.extend(["", "### Resolution route", "", "| Route | Count |", "|---|---:|"])
    for route in ledger["allowed_resolution_routes"]:
        lines.append(f"| {route} | {route_counts[route]} |")
    lines.extend(["", "### Canonical severity", "", "| Severity | Count |", "|---|---:|"])
    for severity in ("critical", "high", "medium", "low", "untriaged"):
        lines.append(f"| {severity} | {severity_counts[severity]} |")
    lines.extend(
        [
            "",
            "## Findings",
            "",
            "| ID | Status | Severity | Lifecycle | Route | Owner | Blockers | Attempts | Source rows | Title |",
            "|---|---|---|---|---|---|---:|---:|---|---|",
        ]
    )
    for finding in ledger["findings"]:
        sources = ", ".join(link["source_id"] for link in finding["source_links"])
        lines.append(
            f"| {finding['finding_id']} | {display_status(finding)} | {finding['severity']} | {finding['lifecycle']} | "
            f"{finding['resolution_route']} | {cell(finding['owner'])} | "
            f"{len(active_blockers(finding))} | {len(finding['verification']['attempts'])} | "
            f"{sources} | {cell(finding['title'])} |"
        )
    lines.extend(
        [
            "",
            "## Source-to-root mapping",
            "",
            "| Source row | Canonical root | Mapping type | Claims | Affected seams | Rationale |",
            "|---|---|---|---|---|---|",
        ]
    )
    mappings: list[tuple[int, str]] = []
    for finding in ledger["findings"]:
        for link in finding["source_links"]:
            row = source_rows[link["source_id"]]
            mappings.append(
                (
                    row["ledger_ordinal"],
                    f"| {link['source_id']} | {link['canonical_root_id']} | "
                    f"{link['mapping_type']} | {cell(', '.join(link['mapped_claims']))} | "
                    f"{cell('; '.join(link['affected_seams']))} | {cell(link['rationale'])} |",
                )
            )
    lines.extend(value for _, value in sorted(mappings))
    lines.extend(
        [
            "",
            "## Update contract",
            "",
            "- Edit `findings.json`, never this generated view.",
            "- Validate every change with `python3 docs/security/remediation/validate_ledger.py --structural`.",
            "- Regenerate with `python3 docs/security/remediation/render_main.py`.",
            "- Use `--layer OWNER` and `--release-candidate SHA` with downloaded external evidence; use `--merged-main SHA` only with the configured committed closure bundle.",
            "- `reopened`, `invalidated`, and `regressed` are history events, never lifecycle values.",
            "- Clearing a blocker sets `closed_date` and appends a matching `blocker_cleared` event; the retained closed record no longer gates release.",
            "- Blockers and upstream routing are separate from lifecycle; neither can make a finding appear complete.",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    rendered = render(load(SOURCE_INDEX), load(FINDINGS))
    # Compare and write BYTES. main.md is a digest-pinned generated artifact, and
    # text mode translates newlines in both directions on Windows: the write
    # would emit CRLF, and `read_text` would then report that CRLF file as equal
    # to the LF rendering. The staleness gate would keep saying "current" while
    # the bytes no longer matched the recorded hash.
    expected = rendered.encode("utf-8")
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_bytes() != expected:
            print("main.md is stale; run render_main.py", file=sys.stderr)
            return 1
        print("main.md is current")
        return 0
    OUTPUT.write_bytes(expected)
    print("rendered main.md")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
